name: PR Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Run SwiftLint
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Run SwiftLint
        run: swiftlint || true

  test:
    name: Run Tests
    needs: lint
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      # Cache DerivedData to speed up builds
      - name: Restore DerivedData Cache
        uses: actions/cache@v3
        with:
          path: Build/DerivedData
          key: xcode-build-${{ hashFiles('**/*.xcodeproj/**') }}
          restore-keys: xcode-build-

      - name: Run Tests in Parallel
        run: |
          set -o pipefail && \
          xcodebuild test \
            -project MonKi.xcodeproj \
            -scheme MonKi \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0.1' \
            -derivedDataPath Build/DerivedData \
            ONLY_ACTIVE_ARCH=YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -parallel-testing-enabled YES \
            -parallel-testing-worker-count 4 \
          | xcbeautify --quiet
